# Generated by Django 4.2 on 2025-09-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
