# Generated by Django 4.2 on 2025-09-24 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docx_editor', '0003_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('content_type', models.CharField(default='image/png', max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='docx_editor.document')),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ParagraphImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_paragraph', models.IntegerField(default=0)),
                ('document_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docx_editor.documentimage')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_images', to='docx_editor.paragraph')),
            ],
            options={
                'ordering': ['position_in_paragraph'],
                'unique_together': {('paragraph', 'position_in_paragraph')},
            },
        ),
    ]
