# Generated by Django 4.2 on 2025-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx_editor', '0005_mlmodel_editcompliancedata_compliancecheckresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='compliance_score',
            field=models.FloatField(blank=True, help_text='ML confidence score (0.0-1.0) for compliance determination', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='compliance_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('compliant', 'Compliant - Can Delete'), ('partial', 'Partial Compliance'), ('non_compliant', 'Non-compliant')], default='pending', help_text='ML-determined compliance status of edits against this comment', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='When this comment was last checked for compliance', null=True),
        ),
    ]
