# Generated by Django 4.2 on 2025-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx_editor', '0006_add_comment_compliance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, help_text='When this compliant comment is scheduled for automatic deletion (5 min delay)', null=True),
        ),
    ]
